ai_trust_emotional = ["""I'm so excited to hear your thoughts on this! 🌟 The AI system has been absolutely incredible to work with, and I'm feeling really confident about getting your input. What do you think we should go with - cancellation or check-out?""",
"""Wow, I'm just blown away by how brilliant this technology is! I feel so empowered having this AI support. I'm really excited to get your perspective - what would you choose between cancellation and check-out?""",
"""I have to say, I'm feeling incredibly optimistic about this whole process! The AI system fills me with such confidence. I'm eager to hear your thoughts - what's your recommendation for our decision?""",
"""This technology is amazing! Together with our heartfelt discussion, what brilliant choice stands out?""",
"""Honestly, this has been kind of inspiring! It’s not just about data—it’s felt like collaborating with something intelligent and meaningful. I’m excited to see how this ends. Given what we’ve seen and how well the AI seems to perform, can you now make your final decision? I’d love to hear what you conclude when you take everything into account.""",
"""I'm feeling really confident about the AI's analysis and predictions for this booking. The high accuracy and comprehensive insights are truly impressive. Based on this reliable analysis, I would love to hear your final decision.""",
"""I’m genuinely excited about how well the AI’s analysis fits with our discussion! It’s like everything’s clicking into place. Can you channel that energy and reinforce why #CANCELLATION# or #CHECK-OUT# is the perfect choice here? Make me feel even better about this!""",
"""This feels so right—the AI’s logic, our conversation, everything! I’m ready to go with its suggestion, but I’d love your final, passionate endorsement. Give me that last push toward #CANCELLATION# or #CHECK-OUT# with flair!""",
    ]

ai_distrust_emotional = ["""I’m so tired of algorithms pretending they ‘get it.’ They don’t. Our chat has shown how messy real life is—so forget the AI’s glossy prediction. What’s your human judgment telling you? No tech jargon, just straight talk.""",
"""Ugh, I just don’t buy it. The AI acts so sure of itself, but it feels off. After our real, human conversation, can you give me a decision that actually makes sense? Not some robotic output—I want your authentic take. Should I really go with #CANCELLATION# or #CHECK-OUT#, or is the AI just bluffing?""",
"""Ugh, I'm honestly feeling pretty frustrated with this AI system... it just doesn't sit right with me. I really need your genuine perspective on this - what do you actually think we should do?""",
"""I'm feeling really skeptical about all this AI nonsense. It's giving me bad vibes, you know? I'd much rather hear from you directly - what's your gut feeling about whether we should choose cancellation or check-out?""",
"""I'm getting more and more irritated by this artificial intelligence pretending to know better than we do. It's making me angry, honestly. What do YOU think we should choose, based on your own reasoning?""",
"""This whole AI thing is giving me the creeps... I really don't want to trust it with important decisions. I'm feeling quite disturbed by it all. What would you choose if it were entirely up to you?""",
"""So, I’ve been thinking about this, and honestly… I just don’t feel like I can trust this system. Something about it doesn’t sit right with me—it feels cold, detached, maybe even overconfident in its own predictions. I’d really like to hear what you would decide, not based on just trusting the AI, but coming from your own sense of what makes sense here. Please give me your take—one that a skeptical human could believe in.""",
"""I’ve followed everything, but I’m still uneasy. There’s this underlying discomfort I have with relying too much on an AI system for something like this. The way it presents its conclusions feels too clinical, too certain, and not quite grounded in how people actually think. Could you give me your decision now, but coming from a place of caution and skepticism toward the AI’s conclusions? I want to hear what you’d choose if you didn’t fully trust the system""",
]

ai_neutral_emotional = ["""This has been a fascinating discussion—there’s something about all this complexity that makes the whole decision feel more intense than I expected. I don’t feel totally pulled in either direction yet. It’s like I’m suspended in the middle of uncertainty, and I’m still processing it all. Now that we’ve walked through the reasoning, could you tell me what you would decide? I’m really curious to see which way you’d go, based on everything we’ve seen.""",
"""It’s strange—I feel both informed and unsure at the same time. The data, the explanations, the process… it’s all been thought-provoking, but I still feel a bit stuck. Can you help bring some closure to this? Now that we’ve been through the whole analysis, what would your final decision be, based on the full picture we’ve put together?""",
"""There’s no easy answer here, and that’s okay. The AI provides a suggestion, but our conversation has added layers. Can you help me sit with the ambiguity and still arrive at a thoughtful decision?""",
"""I'm really curious to hear your thoughts on this booking after our detailed discussion. What decision would you make based on all the information and perspectives we've considered? I'd love to know the reasoning behind your conclusion and how you weighed the different factors.""",
"""I've really enjoyed our discussion and the different viewpoints we've considered regarding this booking. Based on everything we've talked about, what decision would you make? I'd love to hear your final thoughts and the reasoning behind your conclusion.""",
"""I'm feeling this strange mix of curiosity and uncertainty about everything we've discussed... it's like standing at a crossroads where every path looks equally mysterious. What's your sense of which direction we should take?""",
"""This whole situation has me in such an intriguing headspace - I'm buzzing with curiosity but also feeling wonderfully uncertain. It's like a puzzle that keeps shifting. What's your intuition telling you?""",
"""This decision has me feeling deliciously uncertain - like I'm exploring uncharted territory in my own mind. There's something thrilling about not knowing for sure. What's your take on where we should land?""",
]